# Visit https://fossa.com to learn more

version: 3

server: https://app.fossa.com

project:
  id: github.com/AbsaOSS/cobrix
  name: cobrix
  policy: custom-cli-policy
  link: fossa.com
  url: github.com/AbsaOSS/cobrix

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - ".git/**"
      - "**/test/**"
      - "**/target/**"

targets:
  only:
    - type: maven
      path: cobol-parser
    - type: maven
      path: spark-cobol

paths:
  exclude:
    - ./examples
    - "**/target/**"
    - ./project
    - ./cobol-converters

telemetry:
  scope: "off"
