addSbtPlugin("com.github.sbt"    % "sbt-pgp"       % "2.2.1")
addSbtPlugin("com.github.sbt"    % "sbt-release"   % "1.1.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.2.0")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"  % "0.15.0")
addSbtPlugin("com.github.sbt"    % "sbt-jacoco"    % "3.4.0")
