addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "2.0.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.2.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.12")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"  % "0.15.0")
